version: '3.8'

services:
  #  1. ë°±ì—”ë“œ (ì´ë¯¸ì§€ ê°€ì ¸ì˜¤ê¸°)
  backend:
    # âš ï¸ [í•µì‹¬] ë¹Œë“œ(build) ì‚­ì œí•˜ê³  ì´ë¯¸ì§€(image) ì‚¬ìš©
    image: ${DOCKER_IMAGE_BACKEND}
    container_name: timedeal-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # [DB ì—°ê²°]
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      # [ê¸°íƒ€ ì„¤ì •]
      - FRONTEND_URL=${FRONTEND_URL}
      - COOKIE_SECURE=${COOKIE_SECURE}
      # í•„ìš”í•œ ê²½ìš° AWS S3 í‚¤ ë“± ì¶”ê°€
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - TOSS_PAYMENTS_SECRET_KEY=${TOSS_PAYMENTS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY${AWS_SECRET_KEY}
      - REACT_APP_NAVER_MAPS_CLIENT_ID=${REACT_APP_NAVER_MAPS_CLIENT_ID}
      - REACT_APP_NAVER_MAPS_SECRET=${REACT_APP_NAVER_MAPS_SECRET}
      - GONGGONG_KEY=${GONGGONG_KEY}
      - REACT_APP_SGIS_CLIENT_KEY=${REACT_APP_SGIS_CLIENT_KEY}
      - REACT_APP_SGIS_SECRET=${REACT_APP_SGIS_SECRET}
    networks:
      - timedeal-net

      # 2. Nginx (ë¦¬ë²„ìŠ¤ í”„ë¡ì‹œ) - ğŸ‘‡ ì¶”ê°€ëœ ë¶€ë¶„!
  nginx:
    image: nginx:latest
    container_name: timedeal-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # ë£¨íŠ¸ì— ìˆëŠ” nginx.confë¥¼ ì»¨í…Œì´ë„ˆ ì„¤ì •ìœ¼ë¡œ ì—°ê²°
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - timedeal-net

networks:
  timedeal-net:
    driver: bridge

  # 2. í”„ë¡ íŠ¸ì—”ë“œ (ì´ë¯¸ì§€ ê°€ì ¸ì˜¤ê¸°)
#  frontend:
#    # âš ï¸ [í•µì‹¬] ì—¬ê¸°ì„œë„ build, args ì‹¹ ì§€ìš°ê³  ì´ë¯¸ì§€ ì‚¬ìš©!
#    image: ${DOCKER_IMAGE_FRONTEND}
#    container_name: timedeal-frontend
#    restart: always
#    ports:
#      - "80:80"
#    depends_on:
#      - backend
#    networks:
#      - timedeal-net
#

